#!/bin/sh

set -e

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# aerospace 0.19.0

DIR="/tmp"
VERSION="0.19.0-Beta"

if [ ! -d "/Applications/AeroSpace.app" ]; then

    # download
    curl -Lo "$DIR/aerospace.zip" "https://github.com/nikitabobko/AeroSpace/releases/download/v$VERSION/AeroSpace-v$VERSION.zip"

    # extract
    unzip "$DIR/aerospace.zip" -d "$DIR"
    rm -f "$DIR/aerospace.zip"

    # install
    sudo rsync -a "$DIR/AeroSpace-v$VERSION/AeroSpace.app" /Applications/
    sudo xattr -dr com.apple.quarantine "/Applications/AeroSpace.app"
    sudo install -m 755 "$DIR/AeroSpace-v$VERSION/bin/aerospace" /usr/local/bin/aerospace


fi

