#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: autoconf, perl, m4
# Target: Apple Silicon
# automake 1.17

DIR="/tmp"
VERSION="1.17"

if [ ! -f /usr/local/bin/automake ]; then

    # ⚠️ Dependencies
    [ ! -f /usr/local/bin/autoconf ] && ./AUTOCONF  # ✅ Required for automake

    # Download
    curl -Lo $DIR/automake-${VERSION}.tar.gz.sig https://mirrors.ocf.berkeley.edu/gnu/automake/automake-${VERSION}.tar.gz.sig
    curl -Lo $DIR/automake-${VERSION}.tar.gz https://mirrors.ocf.berkeley.edu/gnu/automake/automake-${VERSION}.tar.gz
   
    # Extract
    tar -xzvf $DIR/automake-${VERSION}.tar.gz -C $DIR && rm -f $DIR/automake-${VERSION}.tar.gz
   
    # Install
    (cd $DIR/automake-${VERSION} && ./configure && make && sudo make install)
    
fi
