#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: M4
# Target: Apple Silicon
# autoconf v2.72

DIR="/tmp"
VERSION="2.72"

if [ ! -f /usr/local/bin/autoconf ]; then

    # ⚠️ Dependencies
    [ ! -f /usr/local/bin/m4 ] && ./M4  # ✅ Required for autoconf

    # Download
    curl -Lo $DIR/autoconf-${VERSION}.tar.gz.sig https://mirrors.ocf.berkeley.edu/gnu/autoconf/autoconf-${VERSION}.tar.gz.sig
    curl -Lo $DIR/autoconf-${VERSION}.tar.gz https://mirrors.ocf.berkeley.edu/gnu/autoconf/autoconf-${VERSION}.tar.gz
    
    # Extract
    tar -xzvf $DIR/autoconf-${VERSION}.tar.gz -C $DIR && rm -f $DIR/autoconf-${VERSION}.tar.gz
    
    # Install
    (cd $DIR/autoconf-${VERSION} && ./configure && make && sudo make install)
    
fi


