#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# boost v1.81.0

DIR="/tmp"
VERSION="1.81.0"

if [ ! -d /usr/local/include/boost ]; then

    # Download
    curl -Lo $DIR/boost_${VERSION}.tar.gz https://archives.boost.io/release/${VERSION}/source/boost_${VERSION}.tar.gz

    # Extract
    tar -xzvf $DIR/boost_${VERSION}.tar.gz -C $DIR && rm -f $DIR/boost_${VERSION}.tar.gz

    # Install
    (cd $DIR/boost_${VERSION} && ./bootstrap.sh && sudo ./b2 install)

fi