#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# bzip2 1.0.6

DIR="/tmp"
VERSION="1.0.6"

if [ ! -f /usr/local/lib/libbz2.dylib ]; then

    # Download
    curl -Lo $DIR/bzip2-${VERSION}.tar.gz https://gitlab.com/bzip2/bzip2/-/archive/bzip2-${VERSION}/bzip2-bzip2-${VERSION}.tar.gz

    # Extract
    tar -xzvf $DIR/bzip2-${VERSION}.tar.gz -C $DIR && rm -f $DIR/bzip2-${VERSION}.tar.gz

    # Install
    (cd $DIR/bzip2-bzip2-${VERSION} && make && sudo make install)

fi