#!/bin/sh
set -e

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon

DIR="/tmp"
PKG="Caffeine_1.5.3"
URL="https://dr-caffeine-mac.s3.amazonaws.com/Caffeine_1.5.3.zip"

if [ ! -d "/Applications/Caffeine.app" ]; then

  # download
  curl --fail --location --silent --show-error -o "$DIR/${PKG}.zip" "$URL"

  # extract
  unzip -q "$DIR/${PKG}.zip" -d "$DIR"

  # install
  sudo cp -R "$DIR/Caffeine.app" /Applications

  # cleanup
  rm -rf "$DIR/${PKG}.zip"
  rm -rf "$DIR/Caffeine.app"

fi


