#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: curl, zlib, opt(openssl) 
# Target: Apple Silicon
# cmake v4.0.1

DIR="/tmp"
VERSION="4.0.1"

if [ ! -f /usr/local/bin/cmake ]; then

    # Download
    curl -Lo $DIR/cmake-${VERSION}-SHA-256.txt.asc https://github.com/Kitware/CMake/releases/download/v${VERSION}/cmake-${VERSION}-SHA-256.txt.asc
    curl -Lo $DIR/cmake-${VERSION}.tar.gz https://github.com/Kitware/CMake/releases/download/v${VERSION}/cmake-${VERSION}.tar.gz
    
    # Extract
    tar -xzvf $DIR/cmake-${VERSION}.tar.gz -C $DIR && rm -f $DIR/cmake-${VERSION}.tar.gz
   
    # Install
    (cd $DIR/cmake-${VERSION} && ./bootstrap && make && sudo make install)
    
fi

