#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# erlang 28.0.1

DIR="/tmp"
VERSION="28.0.1"

if [ ! -f /usr/local/bin/erl ]; then

    # ⚠️ Dependencies

    [ ! -f /usr/local/lib/libz.dylib ]       && ./ZLIB         # ✅
    [ ! -f /usr/local/bin/ncursesw6-config ] && ./NCURSES      # ✅
    [ ! -f /usr/local/bin/pkg-config ]       && ./PKGCONFIG    # ✅
    [ ! -f /usr/local/openssl/bin/openssl ]  && ./OPENSSL      # ✅

    # Download

    curl -Lo $DIR/otp_src_${VERSION}.tar.gz https://github.com/erlang/otp/releases/download/OTP-${VERSION}/otp_src_${VERSION}.tar.gz

    # Extract

    tar -xzvf $DIR/otp_src_${VERSION}.tar.gz -C $DIR && rm -f $DIR/otp_src_${VERSION}.tar.gz

    # Install

    (cd $DIR/otp_src_${VERSION} && \
      export LANG=C && \
      ./configure \
        --prefix="/usr/local" \
        --with-ssl=/usr/local/openssl \
        --enable-threads \
        --enable-smp-support \
        --enable-kernel-poll \
        --enable-shared-zlib \
        --without-javac \
        --without-wx \
        --without-odbc \
        --without-termcap \
        && \
      make -j$(sysctl -n hw.ncpu) && \
      sudo make install)

fi

