#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# faad2 2.11.2

DIR="/tmp"
VERSION="2.11.2"

if [ ! -f /usr/local/bin/faad ]; then

    # Download
    curl -Lo "$DIR/faad2.tar.gz" "https://github.com/knik0/faad2/archive/refs/tags/${VERSION}.tar.gz"
    curl -Lo "$DIR/faad2.tar.gz.sig" "https://github.com/knik0/faad2/releases/download/${VERSION}/faad2-${VERSION}.tar.gz.sig"

    # Extract
    tar -xzf "$DIR/faad2.tar.gz" -C "$DIR" && rm -f "$DIR/faad2.tar.gz" "$DIR/faad2.tar.gz.sig"

    # Build and Install
    cd "$DIR/faad2-${VERSION}"
    ./configure --prefix=/usr/local
    make -j"$(sysctl -n hw.ncpu)"
    sudo make install

fi