#!/bin/sh

# ✅ Verified 07/09/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# fast_float v8.0.2

DIR="/tmp"
VERSION="8.0.2"

if [ ! -f /usr/local/include/fast_float/fast_float.h ]; then

    # ⚠️ Dependencies
    [ ! -f /usr/local/bin/cmake ] && ./CMAKE # ✅

    # Download
    curl -Lo "$DIR/fast_float-${VERSION}.tar.gz" "https://github.com/fastfloat/fast_float/archive/refs/tags/v${VERSION}.tar.gz"

    # Extract
    tar -xzvf "$DIR/fast_float-${VERSION}.tar.gz" -C "$DIR" && rm -f "$DIR/fast_float-${VERSION}.tar.gz"

    # Install
    (cd "$DIR/fast_float-${VERSION}" && \
     mkdir build && cd build && \
     cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && \
     make && \
     sudo make install)
fi