#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# fftw v3.3.10

DIR="/tmp"
VERSION="3.3.10"

if [ ! -f /usr/local/lib/libfftw3.dylib ]; then

    # Download
    curl -Lo $DIR/fftw-${VERSION}.tar.gz.md5sum https://www.fftw.org/fftw-${VERSION}.tar.gz.md5sum
    curl -Lo $DIR/fftw-${VERSION}.tar.gz https://www.fftw.org/fftw-${VERSION}.tar.gz

    # Extract
    tar -xzvf $DIR/fftw-${VERSION}.tar.gz -C $DIR && rm -f $DIR/fftw-${VERSION}.tar.gz

    # Install
    (cd $DIR/fftw-${VERSION} && ./configure && make && sudo make install)

fi

