#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: zlib, bzip2, opt(libpng)
# Target: Apple Silicon
# freetype 2.13.3

DIR="/tmp"
VERSION="VER-2-13-3"

if [ ! -f /usr/local/lib/libfreetype.dylib ]; then

    # Download
    curl -Lo $DIR/freetype-${VERSION}.tar.gz https://github.com/freetype/freetype/archive/refs/tags/${VERSION}.tar.gz

    # Extract
    tar xzf $DIR/freetype-${VERSION}.tar.gz -C $DIR && rm -f $DIR/freetype-${VERSION}.tar.gz

    # Install
    (cd $DIR/freetype-${VERSION} && ./autogen.sh && ./configure && make && sudo make install)

fi

