#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: PKGCONFIG
# Target: Apple Silicon
# glib2 2.78.3

DIR="/tmp"
VERSION="2.78.3"

if [ ! -d /usr/local/include/glib-2.0 ]; then

    # Source dependencies
    source "$(dirname "$0")/PKGCONFIG"

    # Download
    curl -Lo "$DIR/glib.tar.xz" "https://download.gnome.org/sources/glib/2.78/glib-${VERSION}.tar.xz"
    curl -Lo "$DIR/glib.tar.xz.sig" "https://download.gnome.org/sources/glib/2.78/glib-${VERSION}.tar.xz.sig"

    # Extract
    tar -xf "$DIR/glib.tar.xz" -C "$DIR" && rm -f "$DIR/glib.tar.xz" "$DIR/glib.tar.xz.sig"

    # Build and Install
    cd "$DIR/glib-${VERSION}"
    meson setup build --prefix=/usr/local
    ninja -C build
    sudo ninja -C build install

fi