#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# icu4c v77.1

DIR="/tmp"
VERSION="77_1"

if [ ! -d /usr/local/lib/icu ]; then

    # Download
    curl -Lo "$DIR/icu4c-${VERSION}-src.tgz.asc" "https://github.com/unicode-org/icu/releases/download/release-77-1/icu4c-77_1-src.tgz.asc"
    curl -Lo "$DIR/icu4c-${VERSION}-src.tgz" "https://github.com/unicode-org/icu/releases/download/release-77-1/icu4c-77_1-src.tgz"

    # Extract
    tar -xzvf "$DIR/icu4c-${VERSION}-src.tgz" -C "$DIR" && rm -f "$DIR/icu4c-${VERSION}-src.tgz"

    # Install
    (cd "$DIR/icu/source" && ./configure --prefix=/usr/local && make -j"$(sysctl -n hw.ncpu)" && sudo make install)

fi