#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# lame 3.100

DIR="/tmp"
VERSION="3.100"

if [ ! -f /usr/local/lib/libmp3lame.dylib ]; then

    # Download
    curl -Lo "$DIR/lame.tar.gz" "https://sourceforge.net/projects/lame/files/lame/${VERSION}/lame-${VERSION}.tar.gz"

    # Extract
    tar -xzvf "$DIR/lame.tar.gz" -C "$DIR" && rm -f "$DIR/lame.tar.gz"

    # Install
    (cd "$DIR/lame-${VERSION}" && ./configure && make && sudo make install)

fi