#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: None
# ⚠️ Dependencies: None
# Target: Apple Silicon
# libao v1.2.0

DIR="/tmp"
VERSION="1.2.0"

if [ ! -f /usr/local/lib/libao.dylib ]; then

    # Download
    curl -Lo $DIR/libao-${VERSION}.tar.gz `https://downloads.xiph.org/releases/ao/libao-${VERSION}.tar.gz`

    # Extract
    tar -xzvf $DIR/libao-${VERSION}.tar.gz -C $DIR && rm -f $DIR/libao-${VERSION}.tar.gz

    # Install
    (cd $DIR/libao-${VERSION} && ./configure && make && sudo make install)

fi