#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# libjpeg-turbo 3.0.0

DIR="/tmp"
VERSION="3.0.0"

if [ ! -f /usr/local/lib/libjpeg.dylib ]; then

    # Download
    curl -Lo "$DIR/libjpeg-turbo.tar.gz" "https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/${VERSION}.tar.gz"

    # Extract
    tar -xzvf "$DIR/libjpeg-turbo.tar.gz" -C "$DIR" && rm -f "$DIR/libjpeg-turbo.tar.gz"

    # Install
    (cd "$DIR/libjpeg-turbo-${VERSION}" && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. && make && sudo make install)

fi

