#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# utf8proc v2.10.0

DIR="/tmp"
VERSION="2.10.0"

if [ ! -f /usr/local/bin/autoconf ]; then

    # Download
    curl -Lo $DIR/v${VERSION}.tar.gz https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v${VERSION}.tar.gz

    # Extract
    tar -xzvf "$DIR/v${VERSION}.tar.gz" -C $DIR && rm -rf "$DIR/v${VERSION}.tar.gz"

    # Install
    (cd "$DIR/utf8proc-${VERSION}" && make && sudo make install)

fi

