#!/bin/sh
set -e

cd /tmp
curl -LO https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.gz
tar -xvf libvorbis-1.3.7.tar.gz
cd libvorbis-1.3.7
sed -i '' 's/-force_cpusubtype_ALL//g' configure || true
sed -i '' 's/-force_cpusubtype_ALL//g' ltmain.sh || true
./configure --disable-examples --disable-oggtest --disable-docs --disable-sharedbook
make -j"$(sysctl -n hw.ncpu)"
sudo make install


