#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# libvterm 0.3.3

DIR="/tmp"
VERSION="0.3.3"

if [ ! -f /usr/local/lib/libvterm.dylib ]; then

    # Download
    curl -Lo $DIR/libvterm-v${VERSION}.tar.gz https://github.com/neovim/libvterm/archive/refs/tags/v${VERSION}.tar.gz

    # Extract
    tar -xzvf "$DIR/libvterm-v${VERSION}.tar.gz" -C $DIR && rm -f "$DIR/libvterm-v${VERSION}.tar.gz"

    # Install
    (cd "$DIR/libvterm-${VERSION}" && make && sudo make install)

fi