#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# x264 stable

DIR="/tmp"

if [ ! -f /usr/local/lib/libx264.dylib ]; then

    # Download
    curl -Lo "$DIR/x264.tar.gz" "https://code.videolan.org/videolan/x264/-/archive/stable/x264-stable.tar.gz"

    # Extract
    tar -xzvf "$DIR/x264.tar.gz" -C "$DIR" && rm -f "$DIR/x264.tar.gz"

    # Install
    (cd "$DIR/x264-stable" && ./configure --enable-shared && make && sudo make install)

fi