#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: LIBUV, LUAJIT
# Target: Apple Silicon
# luv 1.51.0-1

DIR="/tmp"
VERSION="1.51.0-1"

if [ ! -f /usr/local/lib/lua/5.1/luv.so ]; then

    # Download
    curl -Lo "${DIR}/luv-${VERSION}.tar.gz" "https://github.com/luvit/luv/archive/refs/tags/${VERSION}.tar.gz"
    
    # Extract
    tar -xzf "${DIR}/luv-${VERSION}.tar.gz" -C "${DIR}"

    # Install
    cd "${DIR}/luv-${VERSION}" && \
    mkdir -p build && cd build && \
    cmake -DWITH_SHARED_LIBUV=ON \
          -DWITH_LUA_ENGINE=LuaJIT \
          -DLUAJIT_ENABLE_ARM64=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_MODULE=ON \
          -DBUILD_SHARED_LIBS=ON \
          -DLUA_BUILD_TYPE=System .. && \
    cmake --build . && \
    sudo make install

    # Cleanup
    cd "${DIR}" && \
    rm -rf "luv-${VERSION}" "luv-${VERSION}.tar.gz"

fi
