#!/bin/sh

set -e

# ✅ Verified 07/12/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# mas 2.2.2

SRC="mas"
SRC_URL="https://github.com/mas-cli/mas/releases/download/v2.2.2/mas-2.2.2.pkg"
SRC_PKG="$SRC.pkg"
TMP_DIR="/tmp"

if ! command -v mas >/dev/null 2>&1; then

    # Download
    curl --fail --location --silent --show-error -o "$TMP_DIR/$SRC_PKG" "$SRC_URL"

    # Install
    sudo installer -pkg "$TMP_DIR/$SRC_PKG" -target /

    # Clean up
    rm -f "$TMP_DIR/$SRC_PKG"
fi
