#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# mpd v0.24.3

DIR="/tmp"
VERSION="0.24.3"

sudo rm -rf /usr/local/*
sudo rm -rf /tmp/*

if [ ! -f /usr/local/bin/mpd ]; then

    # ⚠️ Dependencies:

    [ ! -f "/usr/local/bin/pkg-config" ]            && ./PKGCONFIG   # ✅
    [ ! -f "/usr/local/bin/ninja" ]                 && ./NINJA       # ✅
    [ ! -f "/usr/local/bin/meson" ]                 && ./MESON       # ✅
    [ ! -f "/usr/local/lib/libz.dylib" ]            && ./ZLIB        # ✅
    [ ! -f "/usr/local/lib/liblzma.dylib" ]         && ./XZ          # ✅
    [ ! -f "/usr/local/lib/libbz2.dylib" ]          && ./BZIP2       # ✅
    [ ! -f "/usr/local/lib/libiconv.dylib" ]        && ./LIBICONV    # ✅
    [ ! -f "/usr/local/lib/libpcre2-8.dylib" ]      && ./PCRE2       # ✅
    [ ! -f "/usr/local/lib/libicuuc.dylib" ]        && ./ICU         # ✅
    [ ! -d "/usr/local/include/glib-2.0" ]          && ./GLIB2       # ✅
    [ ! -d "/usr/local/include/boost" ]             && ./BOOST       # ✅
    [ ! -f "/usr/local/lib/libfmt.dylib" ]          && ./LIBFMT11    # ✅
    [ ! -f "/usr/local/bin/faad" ]                  && ./FAAD2       # ✅
    [ ! -f "/usr/local/lib/libmad.dylib" ]          && ./LIBMAD      # ✅

    # Download
    curl -Lo $DIR/mpd-${VERSION}.tar.xz.sig https://www.musicpd.org/download/mpd/0.24/mpd-${VERSION}.tar.xz.sig
    curl -Lo $DIR/mpd-${VERSION}.tar.xz https://www.musicpd.org/download/mpd/0.24/mpd-${VERSION}.tar.xz

    # Verify signature
    gpg --verify $DIR/mpd-${VERSION}.tar.xz.sig $DIR/mpd-${VERSION}.tar.xz

    # Extract
    tar -xf "$DIR/mpd-${VERSION}.tar.xz" -C $DIR && rm -rf $DIR/mpd-${VERSION}.tar.xz

    # Install
    (cd "$DIR/mpd-${VERSION}" && meson setup build && ninja -C build && sudo ninja -C build install)

fi