#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# msgpack 6.1.0

DIR="/tmp"
VERSION="6.1.0"

if [ ! -f /usr/local/lib/libmsgpackc.dylib ]; then

    # Download
    curl -Lo $DIR/msgpack-c-${VERSION}.tar.gz https://github.com/msgpack/msgpack-c/archive/refs/tags/c-${VERSION}.tar.gz

    # Extract
    tar -xzvf $DIR/msgpack-c-${VERSION}.tar.gz -C $DIR && rm -f $DIR/msgpack-c-${VERSION}.tar.gz

    # Install
    (cd $DIR/msgpack-c-c-${VERSION} && cmake -DMSGPACK_CXX11=ON . && make -j$(nproc) && sudo make install)

fi