#!/bin/sh

set -e

# ✅ Verified 07/12/2025
# ⚠️ Requires: make
# Target: Apple Silicon
# neofetch 7.1.0

DIR="/tmp"
VERSION="7.1.0"
TAR="neofetch-$VERSION.tar.gz"
URL="https://github.com/dylanaraps/neofetch/archive/refs/tags/$VERSION.tar.gz"
SRC_DIR="$DIR/neofetch-$VERSION"

if [ ! -f "/usr/local/bin/neofetch" ]; then

    # download
    curl -Lo "$DIR/$TAR" "$URL"

    # extract
    tar -xzf "$DIR/$TAR" -C "$DIR"
    rm -f "$DIR/$TAR"

    # install
    make -C "$SRC_DIR" PREFIX=/usr/local install

    # clean
    rm -rf "$SRC_DIR"
fi

