#!/bin/sh

# ✅ Verified 10/23/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: ~ 
# Target: Apple Silicon
# nix 2.32.1

DIR="/tmp"
VERSION="2.32.1"

if [ ! -f /nix/var/nix/profiles/default/bin/nix ]; then

    if [ ! -d $HOME/.config/nix ]; then

    	mkdir -p $HOME/.config/nix

    fi
    
    if [ ! -f $HOME/.config/nix/nix.conf ]; then

    	touch $HOME/.config/nix/nix.conf
    	cp $HOME/.wrk_/.cfg/nix/nix.conf $HOME/.config/nix/nix.conf

    fi
   
    (sh curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install)
    
fi

