#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# pkg-config v0.29.2

DIR="/tmp"
VERSION="0.29.2"

if [ ! -f /usr/local/bin/pkg-config ]; then

    # ⚠️ Dependencies: None

    # Download
    curl -Lo "$DIR/pkg-config-${VERSION}.tar.gz.sig" "https://pkgconfig.freedesktop.org/releases/pkg-config-${VERSION}.tar.gz.sig"
    curl -Lo "$DIR/pkg-config-${VERSION}.tar.gz" "https://pkgconfig.freedesktop.org/releases/pkg-config-${VERSION}.tar.gz"

    # Extract

    tar -xzvf "$DIR/pkg-config-${VERSION}.tar.gz" -C "$DIR" && rm -f "$DIR/pkg-config-${VERSION}.tar.gz"

    # ⚠️ FIXES GLIB BUILD ERROR!

    export CFLAGS="-Wno-error=int-conversion -Wno-error=incompatible-pointer-types"
   
    # Install

    (cd "$DIR/pkg-config-${VERSION}" && ./configure --disable-silent-rules --with-internal-glib && make && sudo make install)

fi