#!/bin/bash

set -e

# Function to install a DMG
install_dmg() {
  local DMG_URL="$1"
  local DMG_NAME="$2"
  local APP_NAME="$3"

  echo "Downloading $APP_NAME..."
  curl -L -o "$DMG_NAME" "$DMG_URL"

  echo "Mounting $DMG_NAME..."
  MOUNT_POINT=$(hdiutil attach "$DMG_NAME" | grep "/Volumes/" | awk '{print $3}')

  echo "Copying $APP_NAME to /Applications..."
  cp -R "$MOUNT_POINT/$APP_NAME" /Applications/

  echo "Unmounting $DMG_NAME..."
  hdiutil detach "$MOUNT_POINT"

  rm "$DMG_NAME"
  echo "$APP_NAME has been installed to /Applications."
  echo
}

# ProtonDrive
PROTONDRIVE_DMG_URL="https://proton.me/download/drive/macos/ProtonDrive-2.1.1.dmg"
PROTONDRIVE_DMG_NAME="ProtonDrive-2.1.1.dmg"
PROTONDRIVE_APP_NAME="ProtonDrive.app"
install_dmg "$PROTONDRIVE_DMG_URL" "$PROTONDRIVE_DMG_NAME" "$PROTONDRIVE_APP_NAME"