#!/bin/bash

set -e

# Function to install a DMG
install_dmg() {
  local DMG_URL="$1"
  local DMG_NAME="$2"
  local APP_NAME="$3"

  echo "Downloading $APP_NAME..."
  curl -L -o "$DMG_NAME" "$DMG_URL"

  echo "Mounting $DMG_NAME..."
  MOUNT_POINT=$(hdiutil attach "$DMG_NAME" | grep "/Volumes/" | awk '{print $3}')

  echo "Copying $APP_NAME to /Applications..."
  cp -R "$MOUNT_POINT/$APP_NAME" /Applications/

  echo "Unmounting $DMG_NAME..."
  hdiutil detach "$MOUNT_POINT"

  rm "$DMG_NAME"
  echo "$APP_NAME has been installed to /Applications."
  echo
}

# ProtonPass
PROTONPASS_DMG_URL="https://proton.me/download/PassDesktop/darwin/universal/ProtonPass_1.31.1.dmg"
PROTONPASS_DMG_NAME="ProtonPass_1.31.1.dmg"
PROTONPASS_APP_NAME="ProtonPass.app"
install_dmg "$PROTONPASS_DMG_URL" "$PROTONPASS_DMG_NAME" "$PROTONPASS_APP_NAME"