#!/bin/sh

# ✅ Verified 07/12/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# tmux 3.5a

DIR="/tmp"
VERSION="3.5a"

if [ ! -f /usr/local/bin/tmux ]; then

    # ⚠️ Dependencies:
    # Make sure libevent, ncurses, and pkg-config are installed and in /usr/local

    # Download
    curl -Lo "$DIR/tmux.tar.gz" "https://github.com/tmux/tmux/releases/download/${VERSION}/tmux-${VERSION}.tar.gz"

    # Extract
    mkdir -p "$DIR/tmux-build"
    tar -xzf "$DIR/tmux.tar.gz" -C "$DIR/tmux-build"
    rm -f "$DIR/tmux.tar.gz"

    # Install
    cd "$DIR/tmux-build/tmux-${VERSION}"
    ./configure \
        CFLAGS="-I/usr/local/include" \
        LDFLAGS="-L/usr/local/lib" \
        PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" \
        --enable-utf8proc
    make
    sudo make install


fi
