#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# unibilium v2.0.0

DIR="/tmp"
VERSION="2.0.0"

if [ ! -f /usr/local/lib/libunibilium.dylib ]; then

    # Download
    curl -Lo "$DIR/v${VERSION}.tar.gz" https://github.com/mauke/unibilium/archive/refs/tags/v${VERSION}.tar.gz

    # Extract
    tar -xzvf "$DIR/v${VERSION}.tar.gz" -C "$DIR" && rm -f "$DIR/v${VERSION}.tar.gz"

    # Install
    (cd "$DIR/unibilium-${VERSION}" && make PREFIX=/usr/local CC=clang LIBTOOL=libtool && sudo make install PREFIX=/usr/local LIBTOOL=libtool)

fi