#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# utfcpp v4.0.6

DIR="/tmp"
VERSION="4.0.6"

if [ ! -f /usr/local/include/utf8/checked.h ]; then

    # Download
    curl -Lo "$DIR/v${VERSION}.tar.gz" https://github.com/nemtrif/utfcpp/archive/refs/tags/v${VERSION}.tar.gz

    # Extract
    tar -xzvf "$DIR/v${VERSION}.tar.gz" -C "$DIR" && rm -f "$DIR/v${VERSION}.tar.gz"

    # Install entire utf8 directory
    sudo cp -r "$DIR/utfcpp-${VERSION}/source/utf8" /usr/local/include/

fi
