#!/bin/bash

source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

# Accent Colors
RED=0xfff90000
ORG=0xffff4f00
YLW=0xffffbf00
GRN=0xff00d25a
CYN=0xff00cfc1
BLU=0xff007bff
PNK=0xffff0650

# Monochrome Shades
M01=0xff000206
M02=0xff242424
M03=0xff4f4f4f
M04=0xffc2c1c0
M05=0xffe8e7e6
M06=0xfff0eeed
M07=0xfffbfafa  # EINK_BG

BG=$M05
FG=$M02
FONT="BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons"

##### Bar Appearance #####

sketchybar --bar position=bottom height=40 blur_radius=10 #color=$BAR_COLOR

##### Changing Defaults #####

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Regular:15.0"
  label.font="$FONT:Regular:15.0"
  icon.color=$FG
  label.color=$FG
  icon.padding_left=10
  icon.padding_right=0
  label.padding_left=10
  label.padding_right=10
  background.color=$BG
  background.corner_radius=5
  background.height=24
)
sketchybar --default "${default[@]}"
sketchybar --bar color=0x00000000

##### Left Items #####

sketchybar --add item apple left \
           --set apple icon= label.drawing=off icon.padding_right=10 \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh"  \
           --subscribe front_app front_app_switched

sketchybar --add event aerospace_workspace_change

sketchybar --add item window_title left \
           --set window_title icon=\
                               label.font="SF Pro:Semibold:14.0" \
                               icon.padding_left=0 \
                               width=dynamic \
                               updates=on \
                               update_freq=1 \
                               script="$PLUGIN_DIR/aerospace_window_title.sh" \
          --subscribe window_title aerospace_workspace_change

sketchybar --add item music left \
           --set music \
             script="$PLUGIN_DIR/music.sh" \
             icon= \
             label.padding_left=0 \
             icon.padding_right=8 \
             label.color=0xffa6e3a1 \
             icon.color=0xffa6e3a1 \
             click_script="open -a Spotify" \
             update_freq=2 \
             drawing=off \    # start hidden
           --subscribe music media_change


##### Right Items #####

sketchybar \
  --add item clock right \
    --set clock \
      update_freq=10 \
      icon=􀉉 \
      script="$PLUGIN_DIR/clock.sh" \
  \
  --add item weather right \
    --set weather \
      script="$PLUGIN_DIR/weather.sh" \
      icon= \
      update_freq=300 \
      label.padding_left=0 \
      icon.padding_right=8 \
      label.color=$FG \
      icon.color=$FG \
      click_script="open -a Weather" \
      drawing=on \
  \
  --add item volume right \
    --set volume \
      script="$PLUGIN_DIR/volume.sh" \
      padding_right=4 \
      --subscribe volume volume_change \
  \
  --add item battery right \
    --set battery \
      update_freq=120 \
      script="$PLUGIN_DIR/battery.sh" \
      padding_right=4 \
      --subscribe battery system_woke power_source_change \
  \
  --add item disk right \
    --set disk \
    script="$PLUGIN_DIR/disk.sh" \
    icon= \
     update_freq=3 \
     label.padding_left=0 \
     icon.padding_right=8 \
    label.color=$FG \
    icon.color=$RED \
  \
  --add graph cpu_usage right 50 \
     --set cpu_usage script="$PLUGIN_DIR/cpu_usage.sh" \
      update_freq=5 \
      label.color=$FG \
      graph.color=$BLU \
      graph.fill_color=$BLU \
      graph.line_width=2 \
      icon.drawing=off

##### Force all scripts to run the first time #####
sketchybar --update

sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)


