#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# bison 3.8.2

DIR="/tmp"
VERSION="3.8.2"

if [ ! -f /usr/local/bin/bison ]; then

    # Download
    curl -Lo "$DIR/bison.tar.gz" "https://mirrors.ocf.berkeley.edu/gnu/bison/bison-${VERSION}.tar.gz"
    curl -Lo "$DIR/bison.tar.gz.sig" "https://mirrors.ocf.berkeley.edu/gnu/bison/bison-${VERSION}.tar.gz.sig"

    # Extract
    tar -xzf "$DIR/bison.tar.gz" -C "$DIR" && rm -f "$DIR/bison.tar.gz" "$DIR/bison.tar.gz.sig"

    # Build and Install
    cd "$DIR/bison-${VERSION}"
    ./configure --prefix=/usr/local
    make
    sudo make install

fi