#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# harfbuzz 8.1.1

DIR="/tmp"
VERSION="8.1.1"

if [ ! -f /usr/local/lib/libharfbuzz.dylib ]; then

    # Download
    curl -Lo "$DIR/harfbuzz.tar.gz" "https://github.com/harfbuzz/harfbuzz/archive/refs/tags/${VERSION}.tar.gz"

    # Extract
    tar -xzvf "$DIR/harfbuzz.tar.gz" -C "$DIR" && rm -f "$DIR/harfbuzz.tar.gz"

    # Install
    (cd "$DIR/harfbuzz-${VERSION}" && meson setup build && cd build && ninja && sudo ninja install)


fi