#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: autoconf, automake, libtool, freetype, fontconfig, fribidi, harfbuzz
# libass 0.17.4

DIR="/tmp"
VERSION="0.17.4"

if [ ! -f /usr/local/lib/libass.dylib ]; then

    # ⚠️ Dependencies
    [ ! -f /usr/local/bin/autoconf ]             && ./AUTOCONF      # ✅
    [ ! -f /usr/local/bin/automake ]             && ./AUTOMAKE      # ✅ 
    [ ! -f /usr/local/bin/libtool ]              && ./LIBTOOL       # ✅
    [ ! -f /usr/local/bin/pkg-config ]           && ./PKGCONFIG     # ✅
    [ ! -f /usr/local/lib/libfreetype.dylib ]    && ./FREETYPE      # ✅
    [ ! -f /usr/local/lib/libfontconfig.dylib ]  && ./FONTCONFIG    # ✅
    [ ! -f /usr/local/lib/libfribidi.dylib ]     && ./FRIBIDI       # ✅
    [ ! -f /usr/local/lib/libharfbuzz.dylib ]    && ./HARFBUZZ      # ✅

    # Download
    curl -Lo "$DIR/libass-${VERSION}.tar.gz" "https://github.com/libass/libass/archive/refs/tags/${VERSION}.tar.gz"

    # Extract
    tar -xzvf "$DIR/libass-${VERSION}.tar.gz" -C "$DIR" && rm -f "$DIR/libass-${VERSION}.tar.gz"

    # Install
    (cd "$DIR/libass-${VERSION}" && ./autogen.sh && ./configure && make -j"$(sysctl -n hw.ncpu)" && sudo make install)

fi