#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# libedit 20250104-3.1

DIR="/tmp"
VERSION="20250104-3.1"

if [ ! -f /usr/local/lib/libedit.dylib ]; then

    # Download
    curl -Lo $DIR/libedit-${VERSION}.tar.gz https://www.thrysoee.dk/editline/libedit-${VERSION}.tar.gz

    # Extract
    tar -xzvf $DIR/libedit-${VERSION}.tar.gz -C $DIR && rm -f $DIR/libedit-${VERSION}.tar.gz

    # Install
    (cd $DIR/libedit-${VERSION} && ./configure && make && sudo make install)

fi
