#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# lua 5.4.6

DIR="/tmp"
VERSION="5.4.6"

if [ ! -f /usr/local/bin/lua ]; then

    # Download
    curl -Lo "${DIR}/lua-${VERSION}.tar.gz" "https://www.lua.org/ftp/lua-${VERSION}.tar.gz"
    
    # Extract
    tar -xzf "${DIR}/lua-${VERSION}.tar.gz" -C "${DIR}"

    # Install
    cd "${DIR}/lua-${VERSION}" && \
    make macosx && \
    sudo make install

    # Cleanup
    cd "${DIR}" && \
    rm -rf "lua-${VERSION}" "lua-${VERSION}.tar.gz"

fi