#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# LuaJIT 2.1.ROLLING

DIR="/tmp"
VERSION="2.1.ROLLING"

if [ ! -f /usr/local/lib/libluajit-5.1.dylib ]; then

export MACOSX_DEPLOYMENT_TARGET=11.0

    # Download
    curl -Lo $DIR/LuaJIT-v${VERSION}.tar.gz https://github.com/LuaJIT/LuaJIT/archive/refs/tags/v${VERSION}.tar.gz

    # Extract
    tar -xzvf "$DIR/LuaJIT-v${VERSION}.tar.gz" -C $DIR && rm -f "$DIR/LuaJIT-v${VERSION}.tar.gz"

    # Install
    (cd "$DIR/LuaJIT-${VERSION}" && make MACOSX_DEPLOYMENT_TARGET=11.0 TARGET_CFLAGS="-fno-stack-check" && sudo make install)

fi

