#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: PKGCONFIG
# Target: Apple Silicon
# lz4 1.10.0

DIR="/tmp"
VERSION="1.10.0"

if [ ! -f /usr/local/bin/lz4 ]; then

    # Download
    curl -Lo "$DIR/lz4.tar.gz" "https://github.com/lz4/lz4/archive/refs/tags/v${VERSION}.tar.gz"
    curl -Lo "$DIR/lz4.tar.gz.sig" "https://github.com/lz4/lz4/releases/download/v${VERSION}/v${VERSION}.tar.gz.sig"

    # Extract
    tar -xzf "$DIR/lz4.tar.gz" -C "$DIR" && rm -f "$DIR/lz4.tar.gz" "$DIR/lz4.tar.gz.sig"

    # Install
    cd "$DIR/lz4-${VERSION}"
    make -j"$(sysctl -n hw.ncpu)"
    sudo make install

fi