#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# ncurses v6.5

DIR="/tmp"
VERSION="6.3"

if [ ! -f /usr/local/bin/ncursesw6-config ]; then

    # ⚠️ Dependencies: None

    # Download
    curl -Lo $DIR/ncurses-${VERSION}.tar.gz https://ftp.gnu.org/pub/gnu/ncurses/ncurses-${VERSION}.tar.gz

    # Extract
    tar -xzvf $DIR/ncurses-${VERSION}.tar.gz -C $DIR && rm -f $DIR/ncurses-${VERSION}.tar.gz

    # Install
    (cd $DIR/ncurses-${VERSION} && ./configure --prefix="/usr/local" --with-shared --with-termlib --enable-widec && make && sudo make install)


fi