#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# Target: Apple Silicon
# openssl 3.5.1

DIR="/tmp"
VERSION="3.5.1"


if [ ! -f /usr/local/openssl/bin/openssl ]; then

    # ⚠️ Dependencies None

    # Download

    curl -Lo $DIR/openssl-${VERSION}.tar.gz https://github.com/openssl/openssl/archive/refs/tags/openssl-${VERSION}.tar.gz

    # Extract

    tar -xzvf $DIR/openssl-${VERSION}.tar.gz -C $DIR && rm -f $DIR/openssl-${VERSION}.tar.gz

    # Install

    (cd $DIR/openssl-openssl-${VERSION} && ./Configure darwin64-arm64-cc --prefix="/usr/local/openssl" --openssldir="/usr/local/openssl" && make -j$(sysctl -n hw.ncpu) && sudo make install)

fi