#!/bin/bash

set -e

# Function to install a DMG
install_dmg() {
  local DMG_URL="$1"
  local DMG_NAME="$2"
  local APP_NAME="$3"

  echo "Downloading $APP_NAME..."
  curl -L -o "$DMG_NAME" "$DMG_URL"

  echo "Mounting $DMG_NAME..."
  MOUNT_POINT=$(hdiutil attach "$DMG_NAME" | grep "/Volumes/" | awk '{print $3}')

  echo "Copying $APP_NAME to /Applications..."
  cp -R "$MOUNT_POINT/$APP_NAME" /Applications/

  echo "Unmounting $DMG_NAME..."
  hdiutil detach "$MOUNT_POINT"

  rm "$DMG_NAME"
  echo "$APP_NAME has been installed to /Applications."
  echo
}

# ProtonMail
PROTONMAIL_DMG_URL="https://proton.me/download/mail/macos/1.8.0/ProtonMail-desktop.dmg"
PROTONMAIL_DMG_NAME="ProtonMail-desktop.dmg"
PROTONMAIL_APP_NAME="ProtonMail.app"
install_dmg "$PROTONMAIL_DMG_URL" "$PROTONMAIL_DMG_NAME" "$PROTONMAIL_APP_NAME"
