#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: ncurses
# Target: Apple Silicon
# readline 8.2

DIR="/tmp"
VERSION="8.2"

if [ ! -f /usr/local/lib/libreadline.dylib ]; then

    # Download
    curl -Lo "$DIR/readline-${VERSION}.tar.gz.sig" "https://mirrors.ocf.berkeley.edu/gnu/readline/readline-${VERSION}.tar.gz.sig"
    curl -Lo "$DIR/readline-${VERSION}.tar.gz" "https://mirrors.ocf.berkeley.edu/gnu/readline/readline-${VERSION}.tar.gz"

    # Extract
    tar -xzvf "$DIR/readline-${VERSION}.tar.gz" -C "$DIR" && rm -f "$DIR/readline-${VERSION}.tar.gz"

    # Install
    (cd "$DIR/readline-${VERSION}" && ./configure && make && sudo make install)

fi