#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: git, clang
# Target: Apple Silicon
# SketchyBar 2.22.1

DIR="/tmp"
VERSION="2.22.1"

if [ ! -f /usr/local/bin/sketchybar ]; then

    # download
    git clone --branch "v${VERSION}" https://github.com/FelixKratz/SketchyBar.git "$DIR"

    # extract
    # nothing to do.

    # install
    sudo cp bin/sketchybar /usr/local/bin/

fi
