#!/bin/sh

# ✅ Verified 07/08/2025
# ⚠️ Requires: Signature
# ⚠️ Dependencies: None
# Target: Apple Silicon
# xz 5.8.1

DIR="/tmp"
VERSION="5.8.1"

if [ ! -f /usr/local/lib/liblzma.dylib ]; then

    # Download
    curl -Lo "$DIR/xz-${VERSION}.tar.gz" https://github.com/tukaani-project/xz/releases/download/v${VERSION}/xz-${VERSION}.tar.gz
    curl -Lo "$DIR/xz-${VERSION}.tar.gz.sig" https://github.com/tukaani-project/xz/releases/download/v${VERSION}/xz-${VERSION}.tar.gz.sig

    # Extract
    tar -xzvf "$DIR/xz-${VERSION}.tar.gz" -C "$DIR" && rm -f "$DIR/xz-${VERSION}.tar.gz"

    # Install
    (cd "$DIR/xz-${VERSION}" && ./configure && make -j$(sysctl -n hw.ncpu) && sudo make install)

fi